events { worker_connections 1024; }

http {
    # Define the group of servers we can talk to
    upstream api_cluster {
        # By default, Nginx uses "Round Robin" (1, 2, 3, 1, 2, 3...)
        server api-1:3000;
        server api-2:3000;
        server api-3:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}